#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Aug 20 01:30:53 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=BSL_v8.2.09.zip
enableShaders=true
